create table if not exists checklist_items (
  id integer generated by default as identity primary key,
  task text not null,
  role text not null check (role in ('A1', 'Video', 'Graphics', 'Lighting', 'Stage')),
  section text not null,
  subsection text,
  note text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists checklist_items_sort_order_idx on checklist_items(sort_order, id);
create index if not exists checklist_items_section_idx on checklist_items(section);

create table if not exists runtime_fields (
  id integer generated by default as identity primary key,
  label text not null,
  host text not null,
  port integer not null default 1025 check (port between 1 and 65535),
  clock_number integer not null default 0 check (clock_number >= 0),
  pull_time time not null,
  pull_day integer not null default 0 check (pull_day between 0 and 6),
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists runtime_fields_schedule_idx on runtime_fields(pull_day, pull_time, sort_order, id);

create table if not exists runtime_values (
  id uuid primary key default gen_random_uuid(),
  sunday_id uuid references sundays(id) on delete cascade not null,
  field_id integer references runtime_fields(id) on delete cascade not null,
  value text,
  captured_at timestamptz not null default now(),
  unique(sunday_id, field_id)
);

create index if not exists runtime_values_sunday_idx on runtime_values(sunday_id);
create index if not exists runtime_values_field_idx on runtime_values(field_id);

alter table checklist_items enable row level security;
alter table runtime_fields enable row level security;
alter table runtime_values enable row level security;

drop policy if exists "public_all" on checklist_items;
drop policy if exists "public_all" on runtime_fields;
drop policy if exists "public_all" on runtime_values;

create policy "public_all" on checklist_items for all using (true) with check (true);
create policy "public_all" on runtime_fields for all using (true) with check (true);
create policy "public_all" on runtime_values for all using (true) with check (true);

-- Existing runtime field records were historically entered as 1-based values by the UI.
-- Shift them to ProPresenter's native zero-based indexing once when this migration runs.
update runtime_fields
set clock_number = clock_number - 1
where clock_number > 0;
